{% set name = "cptec-model" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cptec-model-{{ version }}.tar.gz
  sha256: 675abd6fb736ca7ee282486d67ef535dc12998c33cbfbc6c1fa68d3399b8044e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - pynio
  run:
    - python >=3.10
    - numpy
    - pandas
    - matplotlib-base
    - pycurl
    - cfgrib
    - netcdf4
    - pynio
    - xarray
    - dask-core
    - scipy
    - pytest ==7.1.1
    - pytest-json-report    
    - xesmf ==0.3.0 
    
test:
  imports:
    - cptecmodel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://cptec-model.readthedocs.io/en/latest/index.html
  summary: Módulo para distribuição de Modelos Numéricos CPTEC/INPE de forma segmentada/particionada. Com esse pacote o usuário não necessita fazer o Download de todo o volume bruto.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - framework-CPTEC
